name: CI

on: push

jobs:
  builds: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v2
          with:
            version: 8
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpx playwright install chromium
      - run: pnpm run ci
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
